language: node_js
node_js:
  - 0.11
before_script:
  # the 2 following lines are for Firefox
  # http://karma-runner.github.io/0.8/plus/Travis-CI.html
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install libfontconfig
  - npm install bower karma-cli -g
  - bower install